apiVersion: {{ include "app.ingressAPIVersion" . }}
kind: Ingress
metadata:
  annotations:
    {{- if ne (default "" .Values.global.lifetime) "" }}
    synergy.ru/lifetime: "{{ .Values.global.lifetime }}"
    {{- end }}
    {{- if ne (default "" .Values.global.mon_probe) "" }}
    synergy.ru/blackbox.probe: {{ .Values.global.mon_probe }}
    {{- end }}
    {{- if ne (default "" .Values.global.mon_code) "" }}
    synergy.ru/blackbox.code: {{ .Values.global.mon_code }}
    {{- end }}
    {{- if ne (default "" .Values.global.ssl_exp) "" }}
    synergy.ru/ssl.exp: {{ .Values.global.ssl_exp }}
    {{- end }}
    {{- if ne (default "" .Values.global.www_redirect) "no" }}
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    {{- end }}
    {{- if eq .Values.global.env_name "dev" }}
    nginx.ingress.kubernetes.io/auth-url: "http://dev-auth.auth.svc.cluster.local"
    {{- end }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # Additional configuration snippet
      {{- if ne (default "" .Values.block_code) "" }}
      {{- range $index, $country := .Values.block_countries }}
      if ($geoip2_city_country_code = {{ $country.code }}) {
        return {{ $.Values.block_code }};
      }
      {{- end }}
      {{- end }}

      {{- if and (ne .Values.global.ci_path "") (ne .Values.global.ci_path "/") }}
      rewrite ^([^.]*[^/])$ $1/ permanent;
      rewrite (?i)/{{ .Values.global.ci_path | trim | trimAll "/" }}(/|$)(.*) /$2 break;
      {{- end }}
  name: ingress
spec:
  ingressClassName: "nginx"
  rules:
      - host: {{ .Values.global.ci_url | trim }}
        http:
          paths:
            {{- if and (ne .Values.global.ci_path "") (ne .Values.global.ci_path "/") }}
          - path: /{{ .Values.global.ci_path | trim | trimAll "/" }}
            {{- else }}
          - path: /
            {{- end }}
            {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.global.appName }}
                port:
                  name: http
            {{- else }}
            backend:
              serviceName: {{ .Values.global.appName }}
              servicePort: http
            {{- end }}
---
{{- if eq .Values.global.env_name "prod" }}
{{- range $index, $mirror := .Values.mirrors }}
apiVersion: {{ include "app.ingressAPIVersion" $ }}
kind: Ingress
metadata:
  annotations:
    {{- if ne (default "" $.Values.global.lifetime) "" }}
    synergy.ru/lifetime: "{{ $.Values.global.lifetime }}"
    {{- end }}
    {{- if ne (default "" $.Values.global.mon_code) "" }}
    synergy.ru/blackbox.code: {{ $.Values.global.mon_code }}
    {{- end }}
    {{- if ne (default "" $.Values.global.ssl_exp) "" }}
    synergy.ru/ssl.exp: {{ $.Values.global.ssl_exp }}
    {{- end }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # Additional configuration snippet
      {{- if ne (default "" $.Values.block_code) "" }}
      {{- range $index, $country := $.Values.block_countries }}
      if ($geoip2_city_country_code = {{ $country.code }}) {
        return {{ $.Values.block_code }};
      }
      {{- end }}
      {{- end }}

      rewrite ^([^.]*[^/])$ $1/ permanent;

      if ($is_args = '?') {
          rewrite /{{ $mirror.path | trimAll "/" }}(/|$)(.*)   {{ if $mirror.subdir }}{{ $mirror.subdir }}{{ end }}/$2?$args{{- if $mirror.query }}&{{ $mirror.query }}{{- end }}? break;
      }

      if ($is_args = '') {
          rewrite /{{ $mirror.path | trimAll "/" }}(/|$)(.*)   {{ if $mirror.subdir }}{{ $mirror.subdir }}{{ end }}/$2{{- if $mirror.query }}?{{ $mirror.query }}{{- end }} break;
      }

  name: mirror-{{ printf "%s%s" $mirror.host $mirror.path | replace "/" "-" | replace "_" "-" | trimSuffix "-" }}
spec:
  ingressClassName: "nginx"
  rules:
      - host: {{ $mirror.host }}
        http:
          paths:
            {{- if ne $mirror.path "/" }}
          - path: /{{ $mirror.path | trimAll "/" }}
            {{- else }}
          - path: /
            {{- end }}
            {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.global.appName }}
                port:
                  name: http
            {{- else }}
            backend:
              serviceName: {{ $.Values.global.appName }}
              servicePort: http
            {{- end }}
---
{{- range $index, $redirect := $mirror.redirect }}
apiVersion: {{ include "app.ingressAPIVersion" $ }}
kind: Ingress
metadata:
  annotations:
    {{- if ne (default "" $.Values.global.lifetime) "" }}
    synergy.ru/lifetime: "{{ $.Values.global.lifetime }}"
    {{- end }}
    {{- if ne (default "" $.Values.global.mon_code) "" }}
    synergy.ru/blackbox.code: {{ $.Values.global.mon_code }}
    {{- end }}
    {{- if ne (default "" $.Values.global.ssl_exp) "" }}
    synergy.ru/ssl.exp: {{ $.Values.global.ssl_exp }}
    {{- end }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # Additional configuration snippet
      add_header Cache-Control "private, max-age=0, no-cache";

      if ($is_args = '?') {
          rewrite /{{ $redirect.path | trimAll "/" }}(/|$)(.*) https://{{ $mirror.host }}/{{ $mirror.path | trimAll "/" }}/$2?$args? permanent;
      }

      if ($is_args = '') {
          rewrite /{{ $redirect.path | trimAll "/" }}(/|$)(.*) https://{{ $mirror.host }}/{{ $mirror.path | trimAll "/" }}/$2 permanent;
      }

  name: redirect-m-{{ printf "%s%s" $redirect.host $redirect.path | replace "/" "-" | replace "_" "-" | trimSuffix "-" }}
spec:
  ingressClassName: "nginx"
  rules:
      - host: {{ $redirect.host }}
        http:
          paths:
            {{- if ne $redirect.path "/" }}
          - path: /{{ $redirect.path | trimAll "/" }}
            {{- else }}
          - path: /
            {{- end }}
            {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.global.appName }}
                port:
                  name: http
            {{- else }}
            backend:
              serviceName: {{ $.Values.global.appName }}
              servicePort: http
            {{- end }}
---
{{- end }}

{{- end }}
{{- end }}

{{- if eq .Values.global.env_name "prod" }}
{{- range .Values.redirects }}
apiVersion: {{ include "app.ingressAPIVersion" $ }}
kind: Ingress
metadata:
  annotations:
    {{- if ne (default "" $.Values.global.lifetime) "" }}
    synergy.ru/lifetime: "{{ $.Values.global.lifetime }}"
    {{- end }}
    {{- if ne (default "" $.Values.global.mon_code) "" }}
    synergy.ru/blackbox.code: {{ $.Values.global.mon_code }}
    {{- end }}
    {{- if ne (default "" $.Values.global.ssl_exp) "" }}
    synergy.ru/ssl.exp: {{ $.Values.global.ssl_exp }}
    {{- end }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # Additional configuration snippet
      add_header Cache-Control "private, max-age=0, no-cache";

      if ($is_args = '?') {
          rewrite /{{ .path | trimAll "/" }}(/|$)(.*) https://{{ $.Values.global.ci_url }}{{ $.Values.global.ci_path | trimSuffix "/" }}/$2?$args{{- if .query }}&{{ .query }}{{- end }}? permanent;
      }

      if ($is_args = '') {
          rewrite /{{ .path | trimAll "/" }}(/|$)(.*) https://{{ $.Values.global.ci_url }}{{ $.Values.global.ci_path | trimSuffix "/" }}/$2{{- if .query }}?{{ .query }}{{- end }} permanent;
      }

  name: redirect-{{ printf "%s%s" .host .path | replace "/" "-" | replace "_" "-" | trimSuffix "-" }}
spec:
  ingressClassName: "nginx"
  rules:
      - host: {{ .host }}
        http:
          paths:
            {{- if ne .path "/" }}
          - path: /{{ .path | trimAll "/" }}
            {{- else }}
          - path: /
            {{- end }}
            {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.global.appName }}
                port:
                  name: http
            {{- else }}
            backend:
              serviceName: {{ $.Values.global.appName }}
              servicePort: http
            {{- end }}
---
{{- end }}
{{- end }}
